const SAMPLE_CATEGORIES = [
    { id: "1", name: "Electronics & Components", icon: "📱" },
    { id: "2", name: "Apparel & Fashion", icon: "👕" },
    { id: "3", name: "Home & Garden", icon: "🏡" },
    { id: "4", name: "Health & Beauty", icon: "💊" },
    { id: "5", name: "Machinery & Equipment", icon: "🔨" },
    { id: "6", name: "Automotive Parts", icon: "🚗" },
    { id: "7", name: "Construction Materials", icon: "🏗️" },
    { id: "8", name: "Food & Beverages", icon: "🍔" },
    { id: "9", name: "Packaging & Printing", icon: "📦" },
    { id: "10", name: "Sports & Entertainment", icon: "🎮" },
    { id: "11", name: "Textiles & Leather", icon: "👔" },
    { id: "12", name: "Tools & Hardware", icon: "🛠️" },
    { id: "13", name: "Chemical & Plastics", icon: "🧪" },
    { id: "14", name: "Agriculture & Farming", icon: "🌾" },
    { id: "15", name: "Office & School Supplies", icon: "📚" },
  ];


  const SUB_CATEGORIES = {
  "1": [
    { id: "1-1", name: "Mobile Phones & Accessories" },
    { id: "1-2", name: "Computers & Laptops" },
    { id: "1-3", name: "TVs & Home Audio" },
    { id: "1-4", name: "Cameras & Photography" },
    { id: "1-5", name: "Wearable Technology" },
    { id: "1-6", name: "Electronic Components" },
    { id: "1-7", name: "Security & Surveillance" },
    { id: "1-8", name: "Gaming Consoles & Accessories" },
    { id: "1-9", name: "Office Electronics" },
    { id: "1-10", name: "Car & Vehicle Electronics" },
  ],
  "2": [
    { id: "2-1", name: "Men's Apparel" },
    { id: "2-2", name: "Women's Apparel" },
    { id: "2-3", name: "Kids' Apparel" },
    { id: "2-4", name: "Activewear" },
    { id: "2-5", name: "Outerwear" },
    { id: "2-6", name: "Footwear" },
    { id: "2-7", name: "Bags & Luggage" },
    { id: "2-8", name: "Jewelry & Accessories" },
    { id: "2-9", name: "Undergarments & Sleepwear" },
  ],
  "3": [
    { id: "3-1", name: "Furniture" },
    { id: "3-2", name: "Home Decor" },
    { id: "3-3", name: "Kitchen & Dining" },
    { id: "3-4", name: "Bedding & Bath" },
    { id: "3-5", name: "Lighting" },
    { id: "3-6", name: "Gardening Tools & Equipment" },
    { id: "3-7", name: "Outdoor Living" },
    { id: "3-8", name: "Home Improvement Supplies" },
    { id: "3-9", name: "Cleaning Supplies" },
    { id: "3-10", name: "Smart Home Devices" },
  ],
  "4": [
    { id: "4-1", name: "Skincare" },
    { id: "4-2", name: "Makeup" },
    { id: "4-3", name: "Haircare" },
    { id: "4-4", name: "Fragrances" },
    { id: "4-5", name: "Bath & Body" },
    { id: "4-6", name: "Vitamins & Supplements" },
    { id: "4-7", name: "Personal Care Appliances" },
    { id: "4-8", name: "Oral Care" },
    { id: "4-9", name: "Health Monitors & Tests" },
  ],
  "5": [
    { id: "5-1", name: "Heavy Construction Machinery" },
    { id: "5-2", name: "Industrial Manufacturing Equipment" },
    { id: "5-3", name: "Agricultural Machinery" },
    { id: "5-4", name: "Material Handling Equipment" },
    { id: "5-5", name: "Power Generation Equipment" },
    { id: "5-6", name: "Packaging Machinery" },
    { id: "5-7", name: "Textile Machinery" },
    { id: "5-8", name: "Metalworking Machinery" },
    { id: "5-9", name: "Woodworking Machinery" },
    { id: "5-10", name: "Pumps & Compressors" },
  ],
  "6": [
    { id: "6-1", name: "Engine Parts" },
    { id: "6-2", name: "Brake Systems" },
    { id: "6-3", name: "Suspension & Steering" },
    { id: "6-4", name: "Electrical & Lighting Parts" },
    { id: "6-5", name: "Exhaust Systems" },
    { id: "6-6", name: "Automotive Accessories" },
    { id: "6-7", name: "Tires & Wheels" },
    { id: "6-8", name: "Body & Exterior Parts" },
    { id: "6-9", name: "Interior Parts" },
  ],
  "7": [
    { id: "7-1", name: "Cement & Concrete" },
    { id: "7-2", name: "Bricks & Blocks" },
    { id: "7-3", name: "Lumber & Wood Products" },
    { id: "7-4", name: "Steel & Metal Products" },
    { id: "7-5", name: "Roofing Materials" },
    { id: "7-6", name: "Insulation" },
    { id: "7-7", name: "Pipes & Fittings" },
    { id: "7-8", name: "Aggregates (Sand, Gravel)" },
    { id: "7-9", name: "Tiles & Flooring" },
    { id: "7-10", name: "Paints & Coatings" },
  ],
  "8": [
    { id: "8-1", name: "Fresh Produce (Fruits, Vegetables)" },
    { id: "8-2", name: "Meat, Poultry & Seafood" },
    { id: "8-3", name: "Dairy & Eggs" },
    { id: "8-4", name: "Baked Goods & Snacks" },
    { id: "8-5", name: "Beverages (Non-Alcoholic)" },
    { id: "8-6", name: "Alcoholic Beverages" },
    { id: "8-7", name: "Grains, Pasta & Oils" },
    { id: "8-8", name: "Confectionery & Sweets" },
    { id: "8-9", name: "Spices & Condiments" },
  ],
  "9": [
    { id: "9-1", name: "Flexible Packaging" },
    { id: "9-2", name: "Rigid Packaging" },
    { id: "9-3", name: "Paper & Cardboard Packaging" },
    { id: "9-4", name: "Plastic Packaging" },
    { id: "9-5", name: "Metal Packaging" },
    { id: "9-6", name: "Commercial Printing" },
    { id: "9-7", name: "Marketing & Promotional Printing" },
    { id: "9-8", name: "Labels & Tags Printing" },
    { id: "9-9", name: "Packaging Printing" },
    { id: "9-10", name: "Specialty Printing" },
  ],
  "10": [
    { id: "10-1", name: "Team Sports Equipment" },
    { id: "10-2", name: "Individual Sports Equipment" },
    { id: "10-3", name: "Fitness & Exercise Equipment" },
    { id: "10-4", name: "Outdoor Recreation Gear" },
    { id: "10-5", name: "Sports Apparel & Footwear" },
    { id: "10-6", name: "Musical Instruments" },
    { id: "10-7", name: "Board Games & Puzzles" },
    { id: "10-8", name: "Video Games & Accessories" },
    { id: "10-9", name: "Party & Event Supplies" },
  ],
  "11": [
    { id: "11-1", name: "Natural Fibers (Cotton, Silk, Wool)" },
    { id: "11-2", name: "Synthetic Fibers" },
    { id: "11-3", name: "Woven Fabrics" },
    { id: "11-4", name: "Knitted Fabrics" },
    { id: "11-5", name: "Home Textiles (Bedding, Curtains)" },
    { id: "11-6", name: "Industrial Textiles" },
    { id: "11-7", name: "Leather Hides & Skins" },
    { id: "11-8", name: "Leather Apparel" },
    { id: "11-9", name: "Leather Footwear" },
    { id: "11-10", name: "Leather Goods & Accessories" },
  ],
  "12": [
    { id: "12-1", name: "Hand Tools" },
    { id: "12-2", name: "Power Tools" },
    { id: "12-3", name: "Tool Storage & Organization" },
    { id: "12-4", name: "Fasteners (Screws, Nails, Bolts)" },
    { id: "12-5", name: "Adhesives & Sealants" },
    { id: "12-6", name: "Plumbing Hardware" },
    { id: "12-7", name: "Electrical Hardware" },
    { id: "12-8", name: "Locks & Security Hardware" },
    { id: "12-9", name: "Building Hardware" },
  ],
  "13": [
    { id: "13-1", name: "Basic Chemicals" },
    { id: "13-2", name: "Specialty Chemicals" },
    { id: "13-3", name: "Polymers & Resins" },
    { id: "13-4", name: "Plastic Raw Materials" },
    { id: "13-5", name: "Additives & Dyes" },
    { id: "13-6", name: "Adhesives & Sealants (Chemical)" },
    { id: "13-7", name: "Industrial Gases" },
    { id: "13-8", name: "Fine Chemicals" },
    { id: "13-9", name: "Thermoplastics" },
    { id: "13-10", name: "Composites" },
  ],
  "14": [
    { id: "14-1", name: "Crop Production (Grains, Fruits, Vegetables)" },
    { id: "14-2", name: "Animal Production (Livestock, Poultry)" },
    { id: "14-3", name: "Farm Machinery & Equipment" },
    { id: "14-4", name: "Fertilizers & Pesticides" },
    { id: "14-5", name: "Seeds & Seedlings" },
    { id: "14-6", name: "Animal Feed & Supplements" },
    { id: "14-7", name: "Irrigation Systems" },
    { id: "14-8", name: "Aquaculture Products" },
    { id: "14-9", name: "Agricultural Services" },
  ],
  "15": [
    { id: "15-1", name: "Writing Instruments" },
    { id: "15-2", name: "Paper Products" },
    { id: "15-3", name: "Desk Accessories & Organizers" },
    { id: "15-4", name: "Filing & Storage Solutions" },
    { id: "15-5", name: "School Bags & Backpacks" },
    { id: "15-6", name: "Art & Craft Supplies" },
    { id: "15-7", name: "Calculators & Office Electronics" },
    { id: "15-8", name: "Boardroom & Presentation Supplies" },
    { id: "15-9", name: "Educational Supplies" },
  ],
};

export const getCategories = () => {
    return SAMPLE_CATEGORIES;
  };

export const getCategoryById = (id) => {
    return SAMPLE_CATEGORIES.find((category) => category.id === id);
  };

export const getSubCategoriesByMainCategoryId = (id) => {
    return SUB_CATEGORIES[id] || [];
};